import Head from "next/head";
import styles from "../styles/Home.module.css";
export default function Home({ loading }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>DESENVOLVIMENTO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <h1 className="title animeLeft">Aguarde...</h1>}
      <div className={styles.test}>Home</div>
    </div>
  );
}
