import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../src/Components/Header";
import Footer from "../src/Components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Oficial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Pegou</h1>
      <Footer />
    </div>
  );
}
