import Head from "next/head";
import FeedPublic from "../src/Components/FeedPublic/FeedPublic";
export default function Home({ loading }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <FeedPublic />
      </div>
    </div>
  );
}
